apiVersion: v1
kind: Pod
metadata:
  name: exit-code-255-simulation
  labels:
    pod-name: exit-code-255
spec:
  containers:
  - name: exit-code-255
    image: alpine:latest
    command:
      - /bin/sh
      - -c
      - |
        echo "Attempting to execute a command that will fail..."
        # Simulate a failure by trying to run a non-existent command
        non_existent_command || exit 255  # This will cause the pod to exit with code 255
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  restartPolicy: Never  # Do not restart on failure
