apiVersion: v1
kind: Pod
metadata:
  name: exit-code-139-simulation
spec:
  containers:
  - name: exit-code-139
    image: alpine:latest
    command: [
              "/bin/sh", "-c", 
              "apk add --no-cache gcc musl-dev; 
              echo '#include <stdio.h>' > segfault.c; 
              echo 'int main() { int *p = NULL; *p = 0; return 0; }' >> segfault.c; 
              gcc segfault.c -o segfault; 
              ./segfault"
              ]
  restartPolicy: OnFailure
