apiVersion: v1
kind: Pod
metadata:
  name: exit-code-139-fix
spec:
  containers:
  - name: exit-code-139
    image: alpine:latest
    command: [
          "/bin/sh", "-c", 
          "apk add --no-cache gcc musl-dev; 
          echo '#include <stdio.h>' > safe.c; 
          echo 'int main() { int *p = NULL; if (p != NULL) { *p = 0; } return 0; }' >> safe.c; 
          gcc safe.c -o safe; ./safe"]
  restartPolicy: OnFailure