apiVersion: v1
kind: Pod
metadata:
  name: exit-code-137-fix
spec:
  containers:
  - name: exit-code-137
    image: alpine:latest
    command: ["/bin/sh", "-c", "echo 'Allocating memory...'; apk add stress-ng; stress-ng --vm 1 --vm-bytes 1G --timeout 10"]
    resources:
      limits:
        memory: "1G"  # Adjusted limit to prevent OOM
  restartPolicy: OnFailure
