apiVersion: v1
kind: Pod
metadata:
  name: exit-code-2-simulation
spec:
  containers:
  - name: exit-code-2
    image: alpine:latest
    command:
      - /bin/sh
      - -c
      - |
        echo "Starting command with intentional syntax error..."
        if [ missing_bracket  # Incorrect syntax for 'if' statement
        echo "This line won't be executed."
  restartPolicy: OnFailure  # Do not restart on failure
