apiVersion: v1
kind: Pod
metadata:
  name: exit-code-1-fix
spec:
  containers:
  - name: exit-code-1-app
    image: python:alpine3.20  # Use a lightweight Python image
    command: ["python", "-c", "print('Starting application...'); result = 1"]  # Fixed command with no error
  restartPolicy: OnFailure