apiVersion: v1
kind: Pod
metadata:
  name: exit-code-127-fix
spec:
  containers:
  - name: exit-code-127
    image: alpine:latest
    command: ["echo", "This command exists!"]  # Valid command that exists
  restartPolicy: OnFailure