apiVersion: v1
kind: Pod
metadata:
  name: exit-code-127-simulation
spec:
  containers:
  - name: exit-code-127
    image: alpine:latest
    command: ["/bin/sh", "-c", "/non-exist-script.sh"]  # This script does not exist
  restartPolicy: OnFailure
