apiVersion: v1
kind: Pod
metadata:
  name: exit-code-141-fix
spec:
  containers:
  - name: exit-code-141
    image: alpine:latest
    command:
      - /bin/sh
      - -c
      - |
        echo "Generating a SIGPIPE error gracefully..."
        (echo hello; sleep 1; echo world) | {
          tee > /dev/null || echo "Reader process terminated; handling gracefully."
        }
  restartPolicy: Never
