apiVersion: v1
kind: Pod
metadata:
  name: exit-code-141-simulation
spec:
  containers:
  - name: exit-code-141
    image: alpine:latest
    command:
      - /bin/sh
      - -c
      - |
        echo "Generating a SIGPIPE error..."
        (echo hello; sleep 1; echo world) | tee >(echo yo)
  restartPolicy: Never
