apiVersion: v1
kind: Pod
metadata:
  name: exit-code-128-fix
spec:
  containers:
  - name: exit-code-128
    image: alpine:latest
    command: ["echo", "This command exists!"]  # Valid command that exists
  restartPolicy: OnFailure
